# --- tmux Configuration ---
# prefix + I => fetch and install plugins
# prefix + r => reload .tmux.conf file

set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'               # tmux package manager
set -g @plugin 'tmux-plugins/tmux-sensible'     # adds basic tmux configs
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'    # saving and loading tmux states
set -g @plugin 'thewtex/tmux-mem-cpu-load'

# Set theme
set -g @themepack 'powerline/block/cyan'

# Custom prefix
unbind C-b
set -g prefix C-q

# Reload tmux Configuration
unbind r
bind r source-file ~/.tmux.conf \; display "Sourced  ~/.tmux.conf"

# Enable tmux Mouse Mode
set -g mouse on

# Resurret settings
set -g @resurrect-dir '~/tmux/resurrect'      # save destination
set -g @resurrect-strategy-vim 'session'

set -g status-right "#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]"
set -g status-right-length 60

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Clone TMUX plugin manager if not already done
run '~/.tmux/plugins/tpm/tpm'
